# Generated by Django 5.0.7 on 2024-07-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cards',
        ),
        migrations.RenameModel(
            old_name='Coupon',
            new_name='Coupons',
        ),
    ]
