# Generated by Django 5.0.2 on 2024-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0003_cards_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='bank_name',
            field=models.CharField(default='VISA', max_length=120, verbose_name='Bank Name'),
            preserve_default=False,
        ),
    ]
