# Generated by Django 5.0.2 on 2024-07-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0004_cards_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XShop_Books_App.coupons', verbose_name='Coupon'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.BigIntegerField(unique=True, verbose_name='Card Number'),
        ),
    ]
