# Generated by Django 5.0.7 on 2024-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0005_sales_coupon_alter_cards_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total',
            field=models.IntegerField(default=1, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
