# Generated by Django 5.0.7 on 2024-07-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0006_sales_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XShop_Books_App.cards', verbose_name='Card'),
        ),
    ]
