# Generated by Django 5.0.2 on 2024-07-26 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0007_sales_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de expiração'),
            preserve_default=False,
        ),
    ]
