# Generated by Django 5.0.7 on 2024-07-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0009_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='edition',
            field=models.IntegerField(default=1, verbose_name='Edition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='editor',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Editor'),
            preserve_default=False,
        ),
    ]
