# Generated by Django 5.0.7 on 2024-07-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0011_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cart',
        ),
    ]
