# Generated by Django 5.0.7 on 2024-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0016_alter_books_edition_alter_books_editor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='books',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
