# Generated by Django 5.0.7 on 2024-08-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0017_alter_books_edition_alter_books_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='coauthor',
            field=models.CharField(blank=True, default='Unknown', max_length=70, null=True, verbose_name='Co-Autor'),
        ),
    ]
