# Generated by Django 5.0.7 on 2024-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0019_alter_shoppingcart_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='card',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.AddField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(to='XShop_Books_App.shoppingcart', verbose_name='Products'),
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
