# Generated by Django 5.0.7 on 2024-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0020_remove_sales_card_remove_sales_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='products',
            field=models.ManyToManyField(related_name='Products', to='XShop_Books_App.shoppingcart'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Total'),
        ),
    ]
