# Generated by Django 5.0.7 on 2024-08-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XShop_Books_App', '0021_alter_sales_products_alter_sales_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total'),
        ),
    ]
